version: '3'
services:
  houmlab-url-shortener:
    image: mcr.microsoft.com/devcontainers/java:1-21-bullseye
    volumes:
      - .:/workspace
    depends_on:
      - mongo
      - redis
    command: sleep infinity

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_ROOT_URL=http://grafana:3000/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          orgId: 1
          url: http://prometheus:9090
          uid: ds-prometheus
          basicAuth: false
          isDefault: true
          version: 1
          editable: false       
        EOF
        /run.sh
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
     - 'grafana_storage:/var/lib/grafana'
  
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
     - '9090:9090'
    volumes:
     - prometheus_data:/prometheus
    entrypoint:
      - /bin/sh
      - -c
      - |
        cat <<'EOF' > /etc/prometheus/prometheus.yml
        global:
          scrape_interval: 5s
        scrape_configs:
          - job_name: 'url-shortener'
            metrics_path: '/actuator/prometheus'
            static_configs:
              - targets: ['houmlab-url-shortener:8080']
        EOF
        /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.enable-lifecycle

volumes:
  mongodb_data:
  redis_data:
  grafana_storage:
  prometheus_data:  
